import type { SpotWriteInput } from "../spotTypes";

export function buildValidSpotInput(overrides: Partial<SpotWriteInput> = {}): SpotWriteInput {
  return {
    slug: "uradome-coast",
    nameJa: "浦富海岸",
    nameEn: "Uradome Coast",
    shortName: "浦富海岸",
    status: "published",
    primaryCategory: "see",
    secondaryCategories: ["scenery", "beach"],
    tags: ["海景観", "写真映え"],
    location: {
      lat: 35.5868,
      lng: 134.3431,
      geohash: "xn4f4k2",
      addressJa: "鳥取県岩美郡岩美町浦富",
      areaName: "浦富",
      stationAreaType: "none",
    },
    nearestStations: [
      {
        stationId: "iwami-station",
        stationName: "岩美駅",
        distanceMeters: 4600,
        walkMinutes: 58,
      },
    ],
    descriptionShort: "透明度の高い海とリアス式海岸が魅力の景観スポット。",
    descriptionLong: "岩美町の代表景観。短時間立寄りでも満足しやすい。",
    heroImageUrl: null,
    galleryImageUrls: [],
    thumbnailUrl: null,
    websiteUrl: null,
    instagramUrl: null,
    phoneNumber: null,
    operatorName: null,
    business: {
      isAlwaysOpen: true,
      openingHoursText: "終日",
      regularHolidaysText: null,
      reservationRequired: false,
      lastEntryTime: null,
      estimatedStayMinutesMin: 30,
      estimatedStayMinutesMax: 120,
    },
    pricing: {
      priceType: "free",
      priceLabel: "無料",
      priceMinYen: 0,
      priceMaxYen: 0,
    },
    access: {
      supportedTransports: ["walk", "rental_cycle", "car", "bus"],
      parkingAvailable: true,
      bikeParkingAvailable: true,
      busStopNearby: true,
      requiresFirstStop: false,
      requiredFirstStopReason: null,
    },
    plannerAttributes: {
      themes: ["sea_view", "photo"],
      moodTags: ["開放感", "ゆったり"],
      weatherSuitability: {
        sunny: "good",
        cloudy: "ok",
        rainy: "bad",
        windy: "ok",
      },
      timeOfDaySuitability: ["morning", "daytime", "sunset"],
      visitPace: ["short_stop", "normal_stop"],
      withWho: ["solo", "friends", "couple", "family"],
      physicalLoad: "medium",
      indoorOutdoor: "outdoor",
      rainFallbackCandidate: false,
      photoSpotScore: 5,
      scenicScore: 5,
      foodScore: 2,
      shoppingScore: 1,
      experienceScore: 3,
      stationStopoverScore: 2,
      priorityScore: 92,
    },
    aiContext: {
      plannerSummary: "海景観重視の旅で最優先候補にしやすいスポット。",
      whyVisit: ["岩美らしい海岸景観", "写真映え"],
      bestFor: ["海景観重視", "短時間立寄り"],
      avoidIf: ["雨天中心"],
      sampleUseCases: ["海景観と海鮮の日帰り旅"],
    },
    relatedSpotIds: ["iwami-station"],
    campaignCompatible: true,
    couponCompatible: false,
    storyCompatible: true,
    source: "manual",
    lastReviewedAt: null,
    ...overrides,
  };
}
