import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  BadgeCheck,
  BarChart3,
  Bell,
  Beaker,
  Bot,
  Bolt,
  Building2,
  BookOpenText,
  Brain,
  BrainCircuit,
  Bus,
  Car,
  CheckCircle2,
  Cloud,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  Circle,
  CircleDot,
  CircleHelp,
  CirclePlus,
  CircleX,
  CircleUserRound,
  ClipboardList,
  Clock3,
  CloudOff,
  CloudUpload,
  Database,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  Flag,
  FolderOpen,
  Footprints,
  House,
  Image,
  ImagePlus,
  Info,
  Mic2,
  Lock,
  LogIn,
  LogOut,
  Layers,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  ListFilter,
  GripVertical,
  Map,
  MapPin,
  MapPinPlus,
  Mountain,
  Network,
  Pencil,
  PencilLine,
  Play,
  PlayCircle,
  Plus,
  Radar,
  RefreshCw,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Terminal,
  Tablet,
  Ticket,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  Umbrella,
  Undo2,
  Globe,
  Waves,
  X,
  WandSparkles,
  Workflow,
  Route,
  VolumeX,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  add: Plus,
  add_circle: CirclePlus,
  add_photo_alternate: ImagePlus,
  analytics: BarChart3,
  dashboard: LayoutDashboard,
  account_tree: Network,
  architecture: Building2,
  bolt: Bolt,
  arrow_back: ArrowLeft,
  call_split: Workflow,
  arrow_forward: ArrowRight,
  cancel: CircleX,
  close: X,
  auto_awesome: Sparkles,
  auto_fix_high: WandSparkles,
  clinical_notes: ClipboardList,
  auto_stories: BookOpenText,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  filter_alt: ListFilter,
  filter_list: ListFilter,
  cloud_off: CloudOff,
  cloud: Cloud,
  cloud_upload: CloudUpload,
  database: Database,
  delete: Trash2,
  description: FileText,
  directions_bus: Bus,
  directions_car: Car,
  directions_walk: Footprints,
  image: Image,
  edit: Pencil,
  edit_note: PencilLine,
  drag_indicator: GripVertical,
  error: AlertTriangle,
  face: CircleUserRound,
  fact_check: BadgeCheck,
  flag: Flag,
  folder_open: FolderOpen,
  help_outline: CircleHelp,
  history_edu: ScrollText,
  home: House,
  hub: Network,
  info: Info,
  keyboard_double_arrow_left: ChevronsLeft,
  landscape: Mountain,
  light: Lightbulb,
  lightbulb: Lightbulb,
  login: LogIn,
  logout: LogOut,
  local_activity: Ticket,
  location_on: MapPin,
  lock: Lock,
  list_alt: ClipboardList,
  map: Map,
  add_location_alt: MapPinPlus,
  monitoring: Activity,
  more_horiz: Ellipsis,
  more_vert: EllipsisVertical,
  notification_important: AlertTriangle,
  notifications: Bell,
  open_in_new: ExternalLink,
  open_in_full: Tablet,
  pending: Clock3,
  person_search: Search,
  phone_iphone: Smartphone,
  play_arrow: Play,
  play_circle: PlayCircle,
  public: Globe,
  priority_high: AlertTriangle,
  psychology: Brain,
  psychology_alt: BrainCircuit,
  radio_button_checked: CircleDot,
  refresh: RefreshCw,
  radio_button_unchecked: Circle,
  schema: Network,
  sort: ArrowUpDown,
  science: Beaker,
  search: Search,
  send: Send,
  settings: Settings,
  settings_suggest: SlidersHorizontal,
  schedule: Clock3,
  thermostat: Thermometer,
  subscriptions: Layers,
  sync_alt: ArrowLeftRight,
  dynamic_feed: Radar,
  terminal: Terminal,
  theater_comedy: Sparkles,
  trending_up: TrendingUp,
  umbrella: Umbrella,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: AlertTriangle,
  replay: Undo2,
  share: Share2,
  temple_shinto: Landmark,
  tune: SlidersHorizontal,
  tips_and_updates: Lightbulb,
  route: Route,
  menu_book: BookOpenText,
  library_books: BookOpenText,
  network: Network,
  tablet_mac: Tablet,
  insights: BarChart3,
  query_stats: BarChart3,
  model_training: BrainCircuit,
  temp_preferences_custom: Sparkles,
  settings_input_component: SlidersHorizontal,
  record_voice_over: Mic2,
  precision_manufacturing: Settings,
  smart_toy: Bot,
  spatial_audio_off: VolumeX,
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  waves: Waves,
  zap: Zap,
};

export function MaterialIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = iconMap[name] ?? Circle;

  return (
    <Icon
      aria-hidden="true"
      className={className}
      style={{ width: "1em", height: "1em" }}
    />
  );
}
